services:
  kobra-front-app:
    image: ghcr.io/aseca-kobra/kobra-front:latest
    container_name: kobra-front-app
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    restart: unless-stopped
